"""
GPT 2.0 — a decoder-only Transformer, built from scratch following
Andrej Karpathy's "Let's build GPT: from scratch, in code, spelled out"
(nn-zero-to-hero, Lecture 7).

This is the SAME architecture as the lecture (token + position embeddings,
multi-head self-attention with a causal mask, residual connections, LayerNorm,
feed-forward blocks), trained on a DIFFERENT dataset than tiny Shakespeare:
a character-level corpus of public-domain Korean modern literature
(works by 김유정, 현진건, 김동인, 이상, 나도향, 이효석 ... from Wikisource).

Usage
-----
    python gpt.py                  # train with default config, then sample
    python gpt.py --max_iters 1000 # quick run
    python gpt.py --sample_only --resume ckpt.pt   # just generate from a checkpoint

Outputs
-------
    ckpt.pt          model weights + config + vocab
    loss_curve.png   train/val loss vs iteration
    samples.txt      text generated by the trained model

The script auto-detects CUDA / Apple-MPS / CPU, so it will use your GPU if you
have one. Defaults are sized to train in a few minutes on a single GPU and to
still be runnable (slowly) on CPU.
"""

import argparse
import os

import torch
import torch.nn as nn
from torch.nn import functional as F

# ----------------------------------------------------------------------------
# Config (overridable from the command line)
# ----------------------------------------------------------------------------
def get_args():
    p = argparse.ArgumentParser(description="Build & train a GPT (Karpathy lecture 7) on Korean literature.")
    p.add_argument("--data",       type=str,   default="data/input.txt", help="path to training text file")
    p.add_argument("--batch_size", type=int,   default=64)
    p.add_argument("--block_size", type=int,   default=256, help="context length (max tokens of history)")
    p.add_argument("--n_embd",     type=int,   default=384, help="embedding / model dimension")
    p.add_argument("--n_head",     type=int,   default=6,   help="number of attention heads")
    p.add_argument("--n_layer",    type=int,   default=6,   help="number of transformer blocks")
    p.add_argument("--dropout",    type=float, default=0.2)
    p.add_argument("--max_iters",  type=int,   default=5000)
    p.add_argument("--eval_interval", type=int, default=250)
    p.add_argument("--eval_iters", type=int,   default=200)
    p.add_argument("--lr",         type=float, default=3e-4)
    p.add_argument("--seed",       type=int,   default=1337)
    p.add_argument("--out",        type=str,   default="ckpt.pt")
    p.add_argument("--max_new_tokens", type=int, default=2000, help="tokens to generate after training")
    p.add_argument("--resume",     type=str,   default=None, help="checkpoint to resume / sample from")
    p.add_argument("--sample_only", action="store_true", help="skip training, just generate")
    p.add_argument("--device",     type=str,   default=None, help="cuda|mps|cpu (auto if unset)")
    return p.parse_args()


def pick_device(requested=None):
    if requested:
        return requested
    if torch.cuda.is_available():
        return "cuda"
    if getattr(torch.backends, "mps", None) and torch.backends.mps.is_available():
        return "mps"
    return "cpu"


# ----------------------------------------------------------------------------
# Model — exactly the architecture from the lecture
# ----------------------------------------------------------------------------
class Head(nn.Module):
    """One head of causal self-attention."""
    def __init__(self, head_size, n_embd, block_size, dropout):
        super().__init__()
        self.key   = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer("tril", torch.tril(torch.ones(block_size, block_size)))
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B, T, C = x.shape
        k = self.key(x)            # (B,T,hs)
        q = self.query(x)          # (B,T,hs)
        wei = q @ k.transpose(-2, -1) * k.shape[-1] ** -0.5   # (B,T,T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float("-inf"))
        wei = F.softmax(wei, dim=-1)
        wei = self.dropout(wei)
        v = self.value(x)          # (B,T,hs)
        return wei @ v             # (B,T,hs)


class MultiHeadAttention(nn.Module):
    def __init__(self, num_heads, head_size, n_embd, block_size, dropout):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size, n_embd, block_size, dropout) for _ in range(num_heads)])
        self.proj = nn.Linear(head_size * num_heads, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        return self.dropout(self.proj(out))


class FeedForward(nn.Module):
    def __init__(self, n_embd, dropout):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)


class Block(nn.Module):
    """Transformer block: communication (attention) + computation (MLP)."""
    def __init__(self, n_embd, n_head, block_size, dropout):
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size, n_embd, block_size, dropout)
        self.ffwd = FeedForward(n_embd, dropout)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))     # residual + pre-norm attention
        x = x + self.ffwd(self.ln2(x))   # residual + pre-norm MLP
        return x


class GPT(nn.Module):
    def __init__(self, vocab_size, n_embd, n_head, n_layer, block_size, dropout):
        super().__init__()
        self.block_size = block_size
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head, block_size, dropout) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd)
        self.lm_head = nn.Linear(n_embd, vocab_size)
        self.apply(self._init_weights)

    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            nn.init.normal_(module.weight, mean=0.0, std=0.02)
            if module.bias is not None:
                nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            nn.init.normal_(module.weight, mean=0.0, std=0.02)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        device = idx.device
        tok_emb = self.token_embedding_table(idx)                       # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device))  # (T,C)
        x = tok_emb + pos_emb
        x = self.blocks(x)
        x = self.ln_f(x)
        logits = self.lm_head(x)                                        # (B,T,vocab)
        loss = None
        if targets is not None:
            B, T, C = logits.shape
            loss = F.cross_entropy(logits.view(B * T, C), targets.view(B * T))
        return logits, loss

    @torch.no_grad()
    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            idx_cond = idx[:, -self.block_size:]      # crop to block_size
            logits, _ = self(idx_cond)
            logits = logits[:, -1, :]                 # last time step
            probs = F.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, idx_next), dim=1)
        return idx


# ----------------------------------------------------------------------------
# Training
# ----------------------------------------------------------------------------
def main():
    args = get_args()
    device = pick_device(args.device)
    torch.manual_seed(args.seed)
    print(f"device = {device}")

    # ---- data + tokenizer (character-level, just like the lecture) ----
    with open(args.data, "r", encoding="utf-8") as f:
        text = f.read()
    chars = sorted(set(text))
    vocab_size = len(chars)
    stoi = {ch: i for i, ch in enumerate(chars)}
    itos = {i: ch for i, ch in enumerate(chars)}
    encode = lambda s: [stoi[c] for c in s]
    decode = lambda l: "".join(itos[i] for i in l)
    print(f"dataset: {len(text):,} chars | vocab size: {vocab_size}")

    data = torch.tensor(encode(text), dtype=torch.long)
    n = int(0.9 * len(data))
    train_data, val_data = data[:n], data[n:]

    def get_batch(split):
        d = train_data if split == "train" else val_data
        ix = torch.randint(len(d) - args.block_size, (args.batch_size,))
        x = torch.stack([d[i:i + args.block_size] for i in ix])
        y = torch.stack([d[i + 1:i + 1 + args.block_size] for i in ix])
        return x.to(device), y.to(device)

    @torch.no_grad()
    def estimate_loss(model):
        out = {}
        model.eval()
        for split in ("train", "val"):
            losses = torch.zeros(args.eval_iters)
            for k in range(args.eval_iters):
                X, Y = get_batch(split)
                _, loss = model(X, Y)
                losses[k] = loss.item()
            out[split] = losses.mean().item()
        model.train()
        return out

    # ---- build / resume model ----
    model = GPT(vocab_size, args.n_embd, args.n_head, args.n_layer, args.block_size, args.dropout).to(device)
    if args.resume and os.path.exists(args.resume):
        ck = torch.load(args.resume, map_location=device)
        model.load_state_dict(ck["model"])
        itos = ck.get("itos", itos)
        decode = lambda l: "".join(itos[i] for i in l)
        print(f"resumed from {args.resume}")
    n_params = sum(p.numel() for p in model.parameters())
    print(f"model parameters: {n_params/1e6:.2f} M")

    history = {"iter": [], "train": [], "val": []}

    if not args.sample_only:
        optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr)
        for it in range(args.max_iters + 1):
            if it % args.eval_interval == 0 or it == args.max_iters:
                losses = estimate_loss(model)
                history["iter"].append(it)
                history["train"].append(losses["train"])
                history["val"].append(losses["val"])
                print(f"step {it:5d}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")
            xb, yb = get_batch("train")
            _, loss = model(xb, yb)
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            optimizer.step()

        torch.save({"model": model.state_dict(),
                    "config": vars(args),
                    "stoi": stoi, "itos": itos,
                    "history": history}, args.out)
        print(f"saved checkpoint -> {args.out}")
        save_loss_curve(history, "loss_curve.png")

    # ---- generate ----
    context = torch.zeros((1, 1), dtype=torch.long, device=device)
    out = decode(model.generate(context, max_new_tokens=args.max_new_tokens)[0].tolist())
    with open("samples.txt", "w", encoding="utf-8") as f:
        f.write(out)
    print("\n===== sample generation =====\n")
    print(out[:1500])
    print("\nfull sample written to samples.txt")


def save_loss_curve(history, path):
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        plt.figure(figsize=(7, 4.5))
        plt.plot(history["iter"], history["train"], label="train", marker="o", ms=3)
        plt.plot(history["iter"], history["val"], label="val", marker="o", ms=3)
        plt.xlabel("iteration"); plt.ylabel("cross-entropy loss")
        plt.title("GPT on Korean literature — training curve")
        plt.legend(); plt.grid(alpha=0.3); plt.tight_layout()
        plt.savefig(path, dpi=120)
        print(f"saved loss curve -> {path}")
    except Exception as e:
        print(f"(could not plot loss curve: {e})")


if __name__ == "__main__":
    main()
